### ISSUE TITLE
Maybe add a `requirements.txt`?

### ISSUE THREAD

**Issue by Mwalters75** [tnix100/Meower-Server-But-Mongo#1]
This would be more time effective to download all requirements from a `requirements.txt`, than to run the script, to all of the sudden know that you had unmet the requirements.

**Comment by tnix100** [comment]
This isn't really a public thing yet, it only has the files I've modified as backup.

**Comment by Mwalters75** [comment]
So... How about when it is public?

**Comment by Mwalters75** [comment]
Well, it's public now, so...
